---
title: "项目和包的作者名字"
output: github_document
---

>
Name of the copyright holder or holders. Separate multiple individuals with `;`. You can supply a global default with `options(usethis.full_name = "My name")`.

```{r eval=F}
licenses {usethis}	
options(usethis.full_name = "Jiaxiang Li;Ruiqi Wu;Xiaosong Jin")
```

```r
?person
```

可以查看到具体解释

"aut"
(Author) Use for full authors who have made substantial contributions to the package and should show up in the package citation.

"com"
(Compiler) Use for persons who collected code (potentially in other languages) but did not make further substantial contributions to the package.

"cph"
(Copyright holder) Use for all copyright holders.

"cre"
(Creator) Use for the package maintainer.

"ctb"
(Contributor) Use for authors who have made smaller contributions (such as code patches etc.) but should not show up in the package citation.

"ctr"
(Contractor) Use for authors who have been contracted to write (parts of) the package and hence do not own intellectual property.

"dtc"
(Data contributor) Use for persons who contributed data sets for the package.

"fnd"
(Funder) Use for persons or organizations that furnished financial support for the development of the package.

"rev"
(Reviewer) Use for persons or organizations responsible for reviewing (parts of) the package.

"ths"
(Thesis advisor) If the package is part of a thesis, use for the thesis advisor.

"trl"
(Translator) If the R code is a translation from another language (typically S), use for the translator to R.

同时，按照顺序写

```r
## Specifying package authors, example from "boot":
## AC is the first author [aut] who wrote the S original.
## BR is the second author [aut], who translated the code to R [trl],
## and maintains the package [cre].
b <- c(person("Angelo", "Canty", role = "aut", comment =
         "S original, <http://statwww.epfl.ch/davison/BMA/library.html>"),
       person(c("Brian", "D."), "Ripley", role = c("aut", "trl", "cre"),
              comment = "R port", email = "ripley@stats.ox.ac.uk")
     )
b
```
